USE chatop_db;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS rentals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  surface DECIMAL(10, 2) NOT NULL,
  price DECIMAL(12, 2) NOT NULL,
  picture VARCHAR(2048) NOT NULL,
  description VARCHAR(2000) NOT NULL,
  owner_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT pk_rentals PRIMARY KEY (id),
  CONSTRAINT chk_rentals_surface CHECK (surface > 0),
  CONSTRAINT chk_rentals_price CHECK (price >= 0),
  CONSTRAINT fk_rentals_owner
    FOREIGN KEY (owner_id) REFERENCES users (id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  INDEX idx_rentals_owner_id (owner_id)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rental_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  message VARCHAR(2000) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT pk_messages PRIMARY KEY (id),
  CONSTRAINT fk_messages_rental
    FOREIGN KEY (rental_id) REFERENCES rentals (id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_messages_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  INDEX idx_messages_rental_id (rental_id),
  INDEX idx_messages_user_id (user_id)
) ENGINE = InnoDB;
